version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vv8XeY7#pP!daB03hQts
      POSTGRES_DB: fahndung
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: 